
studer_names = [
    "Timestamp",
    "Battery Voltage - L1",
    "Battery Voltage - L2",
    "Battery Voltage - L3",
    "Grid Input Voltage - L1",
    "Grid Input Voltage - L2",
    "Grid Input Voltage - L3",
    "Grid Input Current - L1",
    "Grid Input Current - L2",
    "Grid Input Current - L3",
    "Apparent Power Output - L1",
    "Apparent Power Output - L2",
    "Apparent Power Output - L3",
    "Apparent Power Output w/ External - L1",
    "Apparent Power Output w/ External - L2",
    "Apparent Power Output w/ External - L3",
    "Studer Output Frequency - L1",
    "Studer Output Frequency - L2",
    "Studer Output Frequency - L3",
    "Grid Input Frequency - L1",
    "Grid Input Frequency - L2",
    "Grid Input Frequency - L3",
    "XT-Phase - L1",
    "XT-Phase - L2",
    "XT-Phase - L3",
    "XT-Mode - L1",
    "XT-Mode - L2",
    "XT-Mode - L3",
    "Studer Grid Status - L1",
    "Studer Grid Status - L2",
    "Studer Grid Status - L3",
    "XT-RME - L1",
    "XT-RME - L2",
    "XT-RME - L3",
    "XT-AUX1 - L1",
    "XT-AUX1 - L2",
    "XT-AUX1 - L3",
    "XT-AUX2 - L1",
    "XT-AUX2 - L2",
    "XT-AUX2 - L3",
    "Battery Voltage - L1-1",
    "Battery Voltage - L2-2",
    "Battery Voltage - L3-3",
    "Battery Current - L1-1",
    "Battery Current - L2-2",
    "Battery Current - L3-3",
    "Studer Grid Net Export/Import - L1-1",
    "Studer Grid Net Export/Import - L2-2",
    "Studer Grid Net Export/Import - L3-3",
    "Power Output - L1-1",
    "Power Output - L2-2",
    "Power Output - L3-3",
    "Studer Temperature - L1-1",
    "Studer Temperature - L2-2",
    "Studer Temperature - L3-3",
    "Battery Voltage",
    "Battery Current",
    "Battery State of Charge",
    "Battery Internal Temperature",
    "Solar Power",
    "Dev XT-DBG1",
    "Dev BSP-locE",
    "Dev Sys MSG",
    "Dev Sys SCOM Err"
]

required_studer_columns = [
    "Timestamp",
    "Studer Output Frequency - L1",
    "Studer Output Frequency - L2",
    "Studer Output Frequency - L3",
    "Grid Input Frequency - L1",
    "Grid Input Frequency - L2",
    "Grid Input Frequency - L3",
    "Grid Input Voltage - L1",
    "Grid Input Voltage - L2",
    "Grid Input Voltage - L3",
    "Studer Grid Status - L1",
    "Studer Grid Status - L2",
    "Studer Grid Status - L3",
    "Studer Grid Net Export/Import - L1-1",
    "Studer Grid Net Export/Import - L2-2",
    "Studer Grid Net Export/Import - L3-3",
    "Studer Temperature - L1-1",
    "Studer Temperature - L2-2",
    "Studer Temperature - L3-3",
    "Battery State of Charge",
    "Battery Internal Temperature"
]
